<?php

/**
 * @file
 * Description.
 */

/**
 * Implements hook_theme_registry_alter().
 */
function du_menu_blocks_theme_registry_alter(&$theme_registry) {
  // Add $du_menu_blocks_configuration as a variable to the 'menu' theme hook. Set
  // its default value to be an empty array.
  $theme_registry['menu']['variables']['du_menu_blocks_configuration'] = [];
}

/**
 * Implements hook_theme_suggestions_HOOK() for "menu".
 */
function du_menu_blocks_theme_suggestions_menu_alter(array &$suggestions, array $variables) {
  // The DuSubnav plugin's build() method populates this variable.
  if (!empty($variables['du_menu_blocks_configuration'])) {
    $config = $variables['du_menu_blocks_configuration'];
    $menu_name = strtr($variables['menu_name'], '-', '_');

    $suggestions[] = 'menu__' . $menu_name;

    // Context module (and perhaps others?) adds 'region' into the config.
    if (!empty($config['region'])) {
      $suggestions[] = 'menu__region_' . $config['region'];
      $suggestions[] = 'menu__' . $menu_name . '__region_' . $config['region'];
    }

    // Add our custom theme suggestion.
    if (!empty($config['suggestion']) && $config['suggestion'] !== $menu_name) {
      $suggestions[] = 'menu__' . $config['suggestion'];
    }

    // Context module adds block 'uuid' into the config.
    if (!empty($config['uuid'])) {
      $suggestions[] = 'menu__' . $menu_name . '__' . $config['uuid'];
    }
  }
}
